#%RAML 0.8
title: HATEOAS Inc. Example API
version: v1
baseUri: http://localhost:8000/api/{version}
mediaType: application/vnd.api+json

/users:
    get:
        description: Fetches application users
        responses:
            200
