services:
    api.security.authorization.voter.grant_everything:
        class: "ApiBundle\Security\Authorization\Voter\GrantEverythingVoter"
        public: false
        tags:
            - { name: "security.voter" }

    api.security.authorization.filter.user:
        class: "ApiBundle\Security\Authorization\Voter\UserVoterFilter"
        public: false
        tags:
            - { name: "hateoas.repo_helper.filter" }
